### PR TITLE
openaps/docs dev to spazholio/docs dev

### PR DESCRIPTION
**Pull request by scottleibrand**
This (opened via https://github.com/Spazholio/docs/compare/dev...openaps:dev?expand=1) will merge openaps/docs dev into your dev to get it up to date and clean up your other PR

### CODE REVIEW

**Comment by Spazholio** [comment]
Ok, for future reference - on my workstation, what can I do to make this happen?  Do I need to do a `git fetch upstream` or something?  openaps/dev is set up as `upstream` in my repo.

**Comment by scottleibrand** [comment]
Something like:
git checkout openaps-dev
git pull
git checkout dev
git merge openaps-dev
will do it if you have the openaps-dev branch pointing at the right place.

**Comment by Spazholio** [comment]
I've been referring to `openaps/docs` as `upstream` in my repo.  So I'd be able to checkout something like `upstream/dev` in that scenario?

**Comment by scottleibrand** [comment]
Yeah, that should work. You can give it a try with openaps/docs master branch if you want, and resolve the minor merge conflicts while you're at it (then PR those back into openaps/docs dev). That saves me having to pull out the laptop to do it. :-)

**Comment by Spazholio** [comment]
Sorry to be dense, but I want to be clear - pull the openaps/docs master into spazholio/docs master, then merge spazholio/docs master into spazholio/docs dev, and then resolve those merge conflicts, then PR spazholio/docs dev back to openaps/docs dev?

**Comment by scottleibrand** [comment]
Something like that. Usually you'd make a local openaps-master branch tracking openaps/docs master and pull to there, then merge to dev and do the rest you said. Lots of ways will work though.

**Pull request merged**
